version: '3'

services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - "web:/usr/local/tomcat/webapps"
  
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8081:8080"
    volumes:
      - "web:/shared-directory"
      - "jenkins:/var/jenkins_home/"

volumes:
  jenkins:
  web:
